# Generated by Django 5.2.11 on 2026-03-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
    ]
