# Generated by Django 5.2.11 on 2026-03-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_owner', '0002_rename_name_property_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_name',
            new_name='name',
        ),
    ]
