# Generated by Django 5.2.13 on 2026-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property_owner", "0003_rename_property_name_property_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
