# Generated by Django 5.2.13 on 2026-04-22 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property_owner", "0004_workorder_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorder",
            old_name="property",
            new_name="property_id",
        ),
    ]
